package td.level 
{
	import td.level.LevelEvent;

	public class LevelEvents
	{
		static public var events: Array = [
			[
				new LevelConfig(
					2,
					175,
					[
						[0,1],
						[2,1],
						[4,1],
						[0,3],
						[2,3],
						[4,3],
						[0,5],
						[2,5],
						[4,5],
						[1,6,1],
						[1,7,1]
					]
				),
				[LevelEvent.WAIT, 3],
				[LevelEvent.RAFT, 2],
				[LevelEvent.RAFT, 4],
				[LevelEvent.WAIT, 9],
				[LevelEvent.RAFT, 2],
				[LevelEvent.RAFT, 4],
				[LevelEvent.WAIT, 9],
				[LevelEvent.BOAT, 2],
				[LevelEvent.BOAT, 4],
				[LevelEvent.WAIT, 5],
				[LevelEvent.RAFT, 2],
				[LevelEvent.RAFT, 4],
				[LevelEvent.WAIT, 3],
				[LevelEvent.BOAT, 2],
				[LevelEvent.BOAT, 4]
			],
			[
				new LevelConfig(
					1,
					150,
					[
						[1,1],
						[2,1],
						[5,1],
						[1,3],
						[2,3],
						[5,3],
						[1,5],
						[2,5],
						[5,5],
						[3,6,1],
						[4,7,1]
					]
				),
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 2],
				[LevelEvent.BOAT, 4],
				[LevelEvent.WAIT, 5],
				[LevelEvent.RAFT, 2],
				[LevelEvent.RAFT, 4],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 2],
				[LevelEvent.RAFT, 4],
				[LevelEvent.WAIT, 8],
				[LevelEvent.RAFT, 2],
				[LevelEvent.RAFT, 4],
				[LevelEvent.WAIT, 5],
				[LevelEvent.BOAT, 2],
				[LevelEvent.BOAT, 4],
				[LevelEvent.WAIT, 12],
				[LevelEvent.BOAT, 2],
				[LevelEvent.BOAT, 4],
				[LevelEvent.WAIT, 3],
				[LevelEvent.MOTORBOAT, 2],
				[LevelEvent.MOTORBOAT, 4]
			],
			[
				new LevelConfig(
					1,
					225,
					[
						[0,0],
						[7,0],
						[0,2],
						[7,2],
						[0,4],
						[7,4],
						[0,6],
						[7,6],
						[1,7,1],
						[3,7,1],
						[5,7,1],
					]
				),
				[LevelEvent.WAIT, 2],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 5],
				[LevelEvent.WAIT, 5],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 5],
				[LevelEvent.WAIT, 5],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.WAIT, 7],
				[LevelEvent.MOTORBOAT, 1],
				[LevelEvent.MOTORBOAT, 5],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 5],
				[LevelEvent.WAIT, 3],
				[LevelEvent.MOTORBOAT, 3]
			],
			[
				new LevelConfig(
					2,
					150,
					[
						[0,0],
						[2,0],
						[7,0],
						[0,2],
						[2,2],
						[7,2],
						[0,4],
						[2,4],
						[7,4],
						[0,6],
						[2,6],
						[7,6],
						[1,7,1],
						[3,7,1],
						[5,7],
						[7,7],
						[9,7],
					]
				),
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 4],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 8],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 3],
				[LevelEvent.WAIT, 3],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 5],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.WAIT, 5],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.WAIT, 7],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 5],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 5]
		],
		[
				new LevelConfig(
					5,
					500,
					[
						[0,0],
						[2,0],
						[5,0],
						[4,0],
						[8,0],
						[1,2],
						[2,2],
						[3,2],
						[5,2],
						[1,5],
						[2,5],
						[5,5],
						[3,5],
						[0,7],
						[2,7],
						[4,7],
						[5,7],
						[8,7]
					]
				),
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 4],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 4],
				[LevelEvent.WAIT, 3],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 8],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.WAIT, 8],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 5],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 1],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 5],
				[LevelEvent.MOTORBOAT, 1],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.MOTORBOAT, 6],
				[LevelEvent.WAIT, 8],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 4],
				[LevelEvent.WAIT, 3],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 7],
				[LevelEvent.WAIT, 3],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 7],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.WAIT, 5],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.WAIT, 5],
				[LevelEvent.MOTORBOAT, 1],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.MOTORBOAT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.MOTORBOAT, 1],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.MOTORBOAT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 1],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 1],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 1],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 1],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 1],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.WAIT, 2],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.WAIT, 1],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.WAIT, 1],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.BOAT, 1],
				[LevelEvent.BOAT, 3],
				[LevelEvent.BOAT, 4],
				[LevelEvent.BOAT, 6],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.RAFT, 1],
				[LevelEvent.RAFT, 3],
				[LevelEvent.RAFT, 4],
				[LevelEvent.RAFT, 6],
				[LevelEvent.WAIT, 3],
				[LevelEvent.MOTORBOAT, 1],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.MOTORBOAT, 6],
				[LevelEvent.WAIT, 2],
				[LevelEvent.MOTORBOAT, 1],
				[LevelEvent.MOTORBOAT, 3],
				[LevelEvent.MOTORBOAT, 4],
				[LevelEvent.MOTORBOAT, 6],		]
		];
	}
}
